name: check-pr-screenshots
description: check if merge on develop is from new screenshots
author: valpinkman

runs:
  using: node12
  main: build/index.js

branding:
  icon: user-check
  color: green
