name: Initialize `pdm`
description: Install Python and `pdm` with cache and extract metadata

inputs:
  repository:
    description: Repository to clone (if different from the one doing the workflow)
    required: false
    default: ${{ github.repository }}
  working-directory:
    description: Working directory to use (if not root)
    required: false
    default: ${{ github.workspace }}
  python-version:
    description: Python version to use
  group:
    description: Dependency group(s) to install
    default: ''
  exclude-group:
    description: Dependency group(s) to exclude from install
    default: ''
  history:
    description: Fetch the full history
    required: false
    default: 'false'
  github-token:
    description: A Github token with proper permissions
    required: false
    default: ${{ github.token }}
  skip-dependencies:
    description: Skip dependencies installation

outputs:
  identifier:
    description: The short project identifier
    value: ${{ steps.meta.outputs.identifier }}
  has_tests:
    description: Whether the project has tests exposed through the `test` command
    value: ${{ steps.meta.outputs.has_tests }}
  has_coverage:
    description: Whether the project has tests with coverage exposed through the `cover` command
    value: ${{ steps.meta.outputs.has_coverage }}
  has_docs:
    description: Whether the project has a documentation exposed through the `doc` command
    value: ${{ steps.meta.outputs.has_docs }}
  has_openapi:
    description: Whether the project has an OpenAPI specification exposed through the `doc:openapi` command
    value: ${{ steps.meta.outputs.has_openapi }}
  has_docker:
    description: Whether the project a Docker image (aka. a `Dockerfile` present at root)
    value: ${{ steps.meta.outputs.has_docker }}
  has_src:
    description: Whether the project is using a `src` layout or not
    value: ${{ steps.meta.outputs.has_src }}
  has_backstage:
    description: Whether the project is exposing Backstage catalog infos
    value: ${{ steps.meta.outputs.has_backstage }}
  is_distribution:
    description: Whether the project is a distribution or not
    value: ${{ steps.meta.outputs.is_distribution }}
  is_pr:
    description: Is the current workflow run a pull-request
    value: ${{ steps.meta.outputs.is_pr }}
  branch:
    description: The branch from which workflow has been triggered
    value: ${{ steps.meta.outputs.branch }}
  has_jfrog:
    description: Whether this project uses JFrog Artifactory or not
    value: ${{ steps.detect-jfrog.outputs.has_jfrog }}
  jfrog-domain:
    description: Base domain of Ledger's JFrog platform if authenticated
    value: ${{ steps.jfrog-login.outputs.jfrog-domain }}
  jfrog-url:
    description: Base URL of Ledger's JFrog platform if authenticated
    value: ${{ steps.jfrog-login.outputs.jfrog-url }}
  jfrog-user:
    description: Username extracted from the OIDC token if authenticated
    value: ${{ steps.jfrog-login.outputs.oidc-user }}
  jfrog-token:
    description: OIDC token generated by JFrog CLI if authenticated
    value: ${{ steps.jfrog-login.outputs.oidc-token }}
  python-version:
    description: The Python version used by this action
    value: ${{ steps.setup-pdm.outputs.python-version }}
  pdm-version:
    description: The version of `pdm` used by this action
    value: ${{ steps.setup-pdm.outputs.pdm-version }}


runs:
  using: composite
  steps:
    - name: Clone
      uses: actions/checkout@v4
      with:
        repository: LedgerHQ/ledger-sdk-template
        token: ${{ inputs.github-token }}
        fetch-depth: ${{ inputs.history == 'true' && '0' || '1' }}
