name: Deploy Vault
description: Deploy a Ledger Vault instance

inputs:
  name:
    description: Instance name (must be unique on cluster, lowercase alphanumeric + dash)
    required: true
  owner:
    description: Instance owner (Your name)
    required: true
  expiration:
    description: Instance expiration (in hours)
  preset:
    description: minivault preset to use
  values:
    description: JSON values to override Helm values
    default: "{}"
  environment:
    description: Kubernetes environment (sbx|stg)
    default: sbx

runs:
  using: docker
  image: docker://ghcr.io/ledgerhq/vault-cli:latest
  env:
    REMOTE_URL: https://remote.minivault.ledger-${{ inputs.environment }}.com
  args:
    - deploy
    - --name
    - ${{ inputs.name }}
    - --owner
    - ${{ inputs.owner }}
    - --expirationHours
    - ${{ inputs.expiration }}
    - --preset
    - ${{ inputs.preset }}
    - --remoteURL
    - ${{ env.REMOTE_URL }}
    - --values
    - ${{ inputs.values }}
