name: "Validate and publish"
description: "Run different validation steps on a lib and publish it to a python package index"

inputs:
  python-version:
    description: "Version of python to use"
    required: false
    default: "3.9"
  public:
    description: "if true, push to public python package index pypi.org, otherwise use our private fury.io"
    required: false
    default: "false"
  CI_BOT_TOKEN:
    description: "if specified will be used to checkout submodules recursively in check-version"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - uses: LedgerHQ/actions/python-lib/test@main
      with:
        python-version: ${{ inputs.python-version }}
      env:
        PYPI_DEPLOY_TOKEN: ${{ env.PYPI_DEPLOY_TOKEN }}
        PYPI_FULL_ACCESS_TOKEN: ${{ env.PYPI_FULL_ACCESS_TOKEN }}
    - uses: LedgerHQ/actions/python-lib/check-version@main
      with:
        python-version: ${{ inputs.python-version }}
        CI_BOT_TOKEN: ${{ inputs.CI_BOT_TOKEN }}
    - uses: LedgerHQ/actions/python-lib/publish@main
      with:
        python-version: ${{ inputs.python-version }}
        public: ${{ inputs.public }}
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
        PYPI_PUSH_TOKEN: ${{ env.PYPI_PUSH_TOKEN }}
        PYPI_FULL_ACCESS_TOKEN: ${{ env.PYPI_FULL_ACCESS_TOKEN }}
