name: "Validate and publish"
description: "Run different validation steps on a lib and publish it to a python package index"

inputs:
  python-version:
    description: "Version of python to use"
    required: false
    default: "3.9"
  public:
    description: "if true, push to public python package index pypi.org, otherwise push to our private Gemfury and our internal Nexus"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - uses: LedgerHQ/actions/python-lib/test@main
      with:
        python-version: ${{ inputs.python-version }}
      env:
        GREEN_NEXUS_HOST: ${{ env.GREEN_NEXUS_HOST }}
        GREEN_NEXUS_USER: ${{ env.GREEN_NEXUS_USER }}
        GREEN_NEXUS_PASSWORD: ${{ env.GREEN_NEXUS_PASSWORD }}
        PYPI_DEPLOY_TOKEN: ${{ env.PYPI_DEPLOY_TOKEN }}
        PYPI_FULL_ACCESS_TOKEN: ${{ env.PYPI_FULL_ACCESS_TOKEN }}
    - uses: LedgerHQ/actions/python-lib/check-version@main
      with:
        python-version: ${{ inputs.python-version }}
    - uses: LedgerHQ/actions/python-lib/publish@main
      with:
        python-version: ${{ inputs.python-version }}
        public: ${{ inputs.public }}
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
        GREEN_NEXUS_HOST: ${{ env.GREEN_NEXUS_HOST }}
        GREEN_NEXUS_USER: ${{ env.GREEN_NEXUS_USER }}
        GREEN_NEXUS_PASSWORD: ${{ env.GREEN_NEXUS_PASSWORD }}
        PYPI_PUSH_TOKEN: ${{ env.PYPI_PUSH_TOKEN }}
        PYPI_FULL_ACCESS_TOKEN: ${{ env.PYPI_FULL_ACCESS_TOKEN }}
