# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
ci:
  autoupdate_schedule: weekly
  autoupdate_commit_msg: 'ci(pre-commit): pre-commit.ci autoupdate'
  autofix_commit_msg: 'ci(pre-commit): pre-commit.ci autofixes'

repos:
  - repo: meta
    hooks:
      - id: check-useless-excludes

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: debug-statements
      - id: detect-private-key
      - id: check-merge-conflict

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.28.6
    hooks:
      - id: check-github-actions
        files: ^(.+/)action.ya?ml$
      - id: check-github-workflows
      - id: check-dependabot

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
    - id: codespell
      additional_dependencies: [tomli]
      args: ["--write-changes"]

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.13.0
    hooks:
    - id: markdownlint-cli2
      args: ["--fix"]

  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 2.7.3
    hooks:
    -   id: editorconfig-checker
