name: Build
description: Build and publish image

runs:
  using: "composite"

  steps:
    - name: Check if step is needed
      run: |
        echo docker_needed=${{ startsWith(github.ref, 'refs/tags/') || startsWith(github.ref, 'refs/heads/feature/') || github.ref == 'main' }} >> $GITHUB_ENV
      shell: bash

    - if: ${{ env.docker_needed == 'true' }}
      name: Clone
      uses: actions/checkout@v3

    - if: ${{ env.docker_needed == 'true' }}
      name: Build image name (lowercase)
      run: |
        echo IMAGE="ghcr.io/${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV
      shell: bash

    - if: ${{ env.docker_needed == 'true' }}
      name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ env.IMAGE }}
        flavor: |
            latest=false
        tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr

    - if: ${{ env.docker_needed == 'true' }}
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - if: ${{ env.docker_needed == 'true' }}
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - if: ${{ env.docker_needed == 'true' }}
      name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ env.CI_BOT_USERNAME }}
        password: ${{ env.CI_BOT_TOKEN }}

    - if: ${{ env.docker_needed == 'true' }}
      name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        build-args: PYPI_DEPLOY_TOKEN=${{ env.PYPI_DEPLOY_TOKEN }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        push: true
