name: Build
description: Build and publish image

inputs:
  build-args:
    description: "args to pass to docker build"
    required: false
    default: ""
  platforms:
    description: "args for build platforms (eg: linux/amd64,linux/arm64)"
    required: false
    default: linux/amd64

outputs:
  version:
    description: "Computed Semantic version."
    value: ${{ steps.compute-semantic-version.outputs.semver }}


runs:
  using: "composite"

  steps:
    - name: Check if step is needed
      id: check-docker
      run: |
        #echo "is-docker-needed=${{ startsWith(github.ref, 'refs/tags/') || startsWith(github.head_ref, 'feature/') || github.ref == 'refs/heads/main' }}" >> $GITHUB_OUTPUT
        echo "is-docker-needed=true" >> $GITHUB_OUTPUT
      shell: bash

    - if: ${{ steps.check-docker.outputs.is-docker-needed == 'true' }}
      name: Clone
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # needed for VERSION

    # Authenticate against Docker Hub early to avoid rate-limiting on steps pulling images
    - name: Login to Docker Hub
      if: steps.check-docker.outputs.is-docker-needed == 'true' && env.DOCKERHUB_USERNAME && env.DOCKERHUB_PASSWORD
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ env.DOCKERHUB_PASSWORD }}

    - if: ${{ steps.check-docker.outputs.is-docker-needed == 'true' }}
      name: Info for build
      run: |
        echo VERSION=$(git describe --tags) >> $GITHUB_ENV
        echo "IMAGES<<EOF" >> $GITHUB_ENV
        if [ -n "${JFROG_DOCKER_REPOSITORY}" ]; then
          JFROG_IMAGE=${JFROG_DOMAIN}/${JFROG_DOCKER_REPOSITORY}/${{ github.event.repository.name }}
          echo "${JFROG_IMAGE}" >> $GITHUB_ENV
        fi
        GHCR_IMAGE=ghcr.io/ledgerhq/${{ github.event.repository.name }}
        echo "${GHCR_IMAGE}" >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV
        # Keep only one image as canonical reference
        if [ -n "${JFROG_IMAGE}" ]; then
          echo "IMAGE=${JFROG_IMAGE}" >> $GITHUB_ENV
        else
          echo "IMAGE=${GHCR_IMAGE}" >> $GITHUB_ENV
        fi
      shell: bash

    - if: ${{ steps.check-docker.outputs.is-docker-needed == 'true' }}
      name: Semantic Version preparation
      id: compute-semantic-version
      env:
        REF: ${{ github.event.pull_request && github.head_ref || github.ref_name }}
      run: |
        if [[ $REF =~ ^[0-9]+\.[0-9]+\.[0-9]+(.*)$ ]]; then
          echo "semver=$REF" >> ${GITHUB_OUTPUT}
        else
          echo "semver=0.0.0-${REF//[\/_]/-}" >> ${GITHUB_OUTPUT}
        fi
      shell: bash

    - if: ${{ steps.check-docker.outputs.is-docker-needed == 'true' }}
      name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.IMAGES }}
        flavor: |
            latest=false
        tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=semver,pattern={{version}},value=${{steps.compute-semantic-version.outputs.semver}}

    - if: ${{ steps.check-docker.outputs.is-docker-needed == 'true' }}
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - if: ${{ steps.check-docker.outputs.is-docker-needed == 'true' }}
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        platforms: ${{ inputs.platforms }}

    - name: Authenticate against JFrog Artifactory
      id: jfrog-login
      if: steps.check-docker.outputs.is-docker-needed == 'true' && env.JFROG_REPOSITORY || env.JFROG_DOCKER_REPOSITORY
      uses: LedgerHQ/actions-security/actions/jfrog-login@actions/jfrog-login-1

    - name: Login to JFrog Artifactory internal registry
      if: steps.check-docker.outputs.is-docker-needed == 'true' && env.JFROG_DOCKER_REPOSITORY
      uses: docker/login-action@v3
      with:
        registry: ${{ env.JFROG_DOMAIN }}/${{ env.JFROG_DOCKER_REPOSITORY }}
        username: ${{ env.JFROG_USER }}
        password: ${{ env.JFROG_TOKEN }}

    # Needed for Pipenv only, so has to be done after Docker Authentication
    - name: URL Encode credentials
      if: steps.jfrog-login.outcome == 'success'
      run: |
        : URL Encode credentials
        echo "JFROG_USER=$(echo $JFROG_USER | jq -Rr '@uri')" >> $GITHUB_ENV
        echo "JFROG_TOKEN=$(echo $JFROG_TOKEN | jq -Rr '@uri')" >> $GITHUB_ENV
      shell: bash

    - if: ${{ steps.check-docker.outputs.is-docker-needed == 'true' }}
      name: Build and push
      id: docker_build
      uses: docker/build-push-action@v6
      with:
        context: .
        # See: https://docs.docker.com/build/ci/github-actions/secrets/
        # `Dockerfile` can mount and use the secret at: /run/secrets/PYPI_DEPLOY_TOKEN
        secrets: |
          PYPI_DEPLOY_TOKEN=${{ env.PYPI_DEPLOY_TOKEN }}
          JFROG_USER=${{ env.JFROG_USER }}
          JFROG_TOKEN=${{ env.JFROG_TOKEN }}
        build-args: |
          ${{ inputs.build-args }}
          PYPI_DEPLOY_TOKEN=${{ env.PYPI_DEPLOY_TOKEN }}
          JFROG_REPOSITORY=${{ env.JFROG_REPOSITORY }}
          VERSION=${{ env.VERSION }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        push: true

    - name: Attest Docker image for JFrog Artifactory
      if: steps.check-docker.outputs.is-docker-needed == 'true' && env.JFROG_DOCKER_REPOSITORY
      uses: LedgerHQ/actions-security/actions/attest@actions/attest-1
      with:
        subject-name: ${{ env.IMAGE }}
        subject-digest: ${{ steps.docker_build.outputs.digest }}

    - name: Sign Docker image for JFrog Artifactory
      if: steps.check-docker.outputs.is-docker-needed == 'true' && env.JFROG_DOCKER_REPOSITORY
      uses: LedgerHQ/actions-security/actions/sign-container@actions/sign-container-1
      with:
        tags: ${{ steps.meta.outputs.tags }}
        digest: ${{ steps.docker_build.outputs.digest }}
