name: Build
description: Build and publish image

inputs:
  build-args:
    description: "args to pass to docker build"
    required: false
    default: ""

runs:
  using: "composite"

  steps:
    - name: Check if step is needed
      id: check-docker
      run: |
        echo "::set-output name=is-docker-needed::${{ startsWith(github.ref, 'refs/tags/') || startsWith(github.head_ref, 'feature/') || github.ref == 'refs/heads/main' }}"
      shell: bash

    - if: ${{ steps.check-docker.outputs.is-docker-needed == 'true' }}
      name: Clone
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # needed for VERSION

    - if: ${{ steps.check-docker.outputs.is-docker-needed == 'true' }}
      name: Info for build
      run: |
        # lowercase image name
        echo IMAGE="ghcr.io/${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV
        echo VERSION=$(git describe --tags) >> $GITHUB_ENV
      shell: bash

    - if: ${{ steps.check-docker.outputs.is-docker-needed == 'true' }}
      name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ env.IMAGE }}
        flavor: |
            latest=false
        tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr

    - if: ${{ steps.check-docker.outputs.is-docker-needed == 'true' }}
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - if: ${{ steps.check-docker.outputs.is-docker-needed == 'true' }}
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - if: ${{ steps.check-docker.outputs.is-docker-needed == 'true' }}
      name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ env.CI_BOT_USERNAME || github.actor }}
        password: ${{ env.CI_BOT_TOKEN || github.token }}

    - if: ${{ steps.check-docker.outputs.is-docker-needed == 'true' }}
      name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        build-args: |
          ${{ inputs.build-args }}
          PYPI_DEPLOY_TOKEN=${{ env.PYPI_DEPLOY_TOKEN }}
          VERSION=${{ env.VERSION }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        push: true
