name: "Install fury"
description: "Install fury CLI tool on ubuntu"

runs:
  using: "composite"
  steps:
    - name: Install gemfury
      run: |
        sudo sh -c "echo 'deb [trusted=yes] https://cli.gemfury.com/apt/ /' > /etc/apt/sources.list.d/fury-cli.list"
        sudo apt update
        sudo apt install -y gemfury
      shell: bash
