name: "Publish Helm Chart on chart museum"
description: "Publish Helm Chart on chart museum."

inputs:
  version:
    description: "Specify the chart version to publish."
    required: true
  charts-path:
    description: "Specify the path where the charts are located (no trailing slash)."
    required: false
    default: "./helm/charts"
  chartmuseum-url:
    description: "Specify the URL of Chart Museum"
    required: true
  chartmuseum-user:
    description: "Specify the user of Chart Museum"
    required: true
  chartmuseum-password:
    description: "Specify the password of Chart Museum"
    required: true
  force:
    description: "Replace charts if it exists"
    required: false

runs:
  using: "composite"
  steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Add chartmuseum helm repo
        shell: bash
        run: |
          if ! helm plugin list | grep -q "cm-push"; then
            helm plugin install https://github.com/chartmuseum/helm-push.git
          fi
          helm repo add chartmuseum --username ${{ inputs.chartmuseum-user }} --password ${{ inputs.chartmuseum-password }} ${{ inputs.chartmuseum-url }} &&
          helm repo update
      - name: Push chart to chartmuseum repo
        shell: bash
        run: |
          charts_path="${{ inputs.charts-path }}"
          charts_path_trimmed="${charts_path%/}"
          for chart_file in $charts_path_trimmed/*/Chart.yaml; do
            chart_dir=$(dirname "$chart_file")
            helm cm-push ${{ inputs.force == 'true' && '-f' || ''}} "$chart_dir" chartmuseum --version "${{ inputs.version }}"
          done
