name: Release
description: |
  Bump version and publish release assets

  For JFrog Artifactory, repository needs to be authorized on Artifactory.
  Calling workflow need to have OIDC permissions:

  ```yaml
    permissions:
      id-token: write
  ```

inputs:
  version:
    description: Force a version (won't use commitizen)
    required: false
    default: ""
  working-directory:
    description: Working directory if not the root of the repository
    required: false
    default: ${{ github.workspace }}
  require-clone:
    description: clone the repository
    required: false
    default: "true"
  kind:
    description: DEPRECATED (Set `tool.pdm.distribution=true` on libraries)
    default: ""
  pypi-token:
    description: A Token to publish on PyPI (private or public)
    required: false
  github-token:
    description: A Github token with proper permissions
    required: true
  increment:
    description: "Kind of increment (optional: `MAJOR|MINOR|PATCH`)"
    required: false
  group:
    description: Dependency group(s) to install
    default: docs
  exclude-group:
    description: Dependency group(s) to exclude from install
    default: ''
  public:
    description: Is it a public library ?
    default: 'false'
  dgoss-args:
    description: "`dgoss` extra docker parameters"
    default: ""
  artifactory-repository:
    description: DEPRECATED (Use `JFROG_REPOSITORY` environment variable)
    default: ""
  docker-name:
    description: Optionally override the docker image name (default to the repository name)
    default: ""
  extra-docker:
    description: An optional extra docker image to build
    default: ""
  python-version:
    description: Python version used to build


outputs:
  url:
    description: The generated Github Release URL
    value: ${{ steps.release.outputs.url }}
  version:
    description: The released version
    value: ${{ steps.bump.outputs.version }}
  documentation:
    description: The released documentation URL
    value: ${{ steps.doc.outputs.url }}
  docker:
    description: The released docker image URL
    value: ${{ steps.docker.outputs.image }}
  extra-docker:
    description: The released additional docker image URL
    value: ${{ steps.extra-docker.outputs.image }}


runs:
  using: composite
  steps:
    - name: Handle deprecations
      run: |
        : Handle deprecations
        if [ "${{ inputs.artifactory-repository }}" != "" ]; then
          echo "⚠️ \`artifactory-repository\` input is deprecated, use the \`JFROG_REPOSITORY\` environment variable"
          echo "JFROG_REPOSITORY=${{ inputs.artifactory-repository }}" >> $GITHUB_ENV
        fi
        if [ "${{ inputs.kind }}" != "" ]; then
          echo "⚠️ \`input\` input is deprecated, set \`tool.pdm.distribution=true\` in \`pyproject.toml\` instead"
        fi
      shell: bash
    - name: Clone and install dependencies
      if: inputs.require-clone == 'true'
      uses: LedgerHQ/actions/pdm/init@main
      id: meta
      with:
        group: ${{ inputs.group }}
        exclude-group: ${{ inputs.exclude-group }}
        history: true
        github-token: ${{ inputs.github-token }}
        python-version: ${{ inputs.python-version }}

    - name: Bump using commitizen
      id: bump
      if: inputs.version == ''
      working-directory: ${{ inputs.working-directory }}
      run: |
        : Bump using commitizen
        CMD=('pdm' 'bump' '--changelog-to-stdout' '--git-output-to-stderr')
        if [[ $INPUT_INCREMENT ]]; then
          CMD+=('--increment' "$INPUT_INCREMENT")
        fi
        "${CMD[@]}" > body.md

        REV="$(pdm run cz version --project)"
        echo "REVISION=${REV}" >>"$GITHUB_ENV"
        echo "version=${REV}" >>"$GITHUB_OUTPUT"
      env:
        FORCE_COLOR: 'true'
        INPUT_INCREMENT: ${{ inputs.increment }}
      shell: bash
    - name: set the version
      if: inputs.version != ''
      working-directory: ${{ inputs.working-directory }}
      run: |
        : Set version to be build
        echo "__version__ = '${{ inputs.version }}'" > VERSION
      shell: bash

    # Build once to publish the same package on every repository
    - name: Build distribution
      if: inputs.kind == 'lib' || steps.meta.outputs.is_distribution == 'true'
      working-directory: ${{ inputs.working-directory }}
      run: |
        : Build distribution
        pdm build
      env:
        FORCE_COLOR: 'true'
      shell: bash

    ################################################################
    #                                                              #
    #                  💥 Side-effect zone 💥                      #
    #                                                              #
    # Successful actions will need cleanup 🧹 in case of failure ! #
    #                                                              #
    ################################################################

    - name: Push to our internal JFrog Artifactory
      id: artifactory
      working-directory: ${{ inputs.working-directory }}
      if: (inputs.kind == 'lib' || steps.meta.outputs.is_distribution == 'true') && inputs.public != 'true' && env.JFROG_REPOSITORY
      env:
        PDM_PUBLISH_REPO: ${{ env.JFROG_URL }}/artifactory/api/pypi/${{ env.JFROG_REPOSITORY }}
        PDM_PUBLISH_USERNAME: ${{ env.JFROG_USER }}
        PDM_PUBLISH_PASSWORD: ${{ env.JFROG_TOKEN }}
        FORCE_COLOR: 'true'
      run: |
        : Push to our internal JFrog Artifactory
        echo ${{ env.JFROG_USER }}
        echo ${{ env.JFROG_TOKEN }}
        pdm publish --no-build
      shell: bash

    - name: Attest
      if: steps.artifactory.outcome == 'success'
      uses: LedgerHQ/actions-security/actions/attest@actions/attest-1
      with:
        subject-path: ${{ inputs.working-directory}}/dist/*

    - name: Sign
      if: steps.artifactory.outcome == 'success'
      uses: LedgerHQ/actions-security/actions/sign-blob@actions/sign-blob-1
      with:
        path: ${{ inputs.working-directory}}/dist/*

    - name: Push to PyPI
      id: pypi
      working-directory: ${{ inputs.working-directory }}
      if: (inputs.kind == 'lib' || steps.meta.outputs.is_distribution == 'true') && inputs.public == 'true' && env.PDM_PUBLISH_PASSWORD != null
      env:
        PDM_PUBLISH_PASSWORD: ${{ inputs.pypi-token }}
        FORCE_COLOR: 'true'
      run: |
        : Push to PyPI
        pdm publish --no-build
      shell: bash

    #################################################################################################
    #                                                                                               #
    #                                     🧹 Cleanup actions 🧹                                     #
    #                                                                                               #
    # You must ensure workflow always reach this point in case of failure in the side-effect zone ! #
    #                                                                                               #
    #################################################################################################

    # Cleanup published artifacts if tag push failed
    - name: Show release failure in summary
      if: failure()
      run: |
        : Show release failure in summary
        echo "❌ Release ${REVISION} failed" | tee -a $GITHUB_STEP_SUMMARY
        echo "DIST=${{ steps.meta.outputs.identifier }}" >> $GITHUB_ENV
      shell: bash

    - name: Cleanup documentation
      # Runs on release failure if doc has been published
      if: failure() && steps.doc.outcome == 'success'
      run: |
        : Cleanup documentation
        pdm run mike delete --push ${REVISION}
        echo "🧹 Documentation for version ${REVISION} has been removed" | tee -a $GITHUB_STEP_SUMMARY
      shell: bash

    - name: Cleanup docker GHCR image
      # Runs on release failure if docker has been published
      if: failure() && steps.docker.outcome == 'success'
      run: |
        : Cleanup docker GHCR image
        # See:
        #   - https://docs.github.com/en/rest/packages/packages#list-package-versions-for-a-package-owned-by-an-organization
        #   - https://docs.github.com/en/rest/packages/packages#delete-package-version-for-an-organization
        GHAPI=("gh" "api" "-H" "Accept: application/vnd.github+json" "-H" "X-GitHub-Api-Version: 2022-11-28")
        PKG='${{ github.event.repository.name }}'
        VERSIONS=$(${GHAPI[@]} /orgs/LedgerHQ/packages/container/${PKG}/versions)
        QUERY='.[] | select(.name == "${{ steps.docker.outputs.digest }}") | .id'
        VERSION_ID=$(echo ${VERSIONS} | jq --raw-output ${QUERY})
        ${GHAPI[@]} --method DELETE /orgs/LedgerHQ/packages/container/${PKG}/versions/${VERSION_ID}
        IMAGE="ghcr.io/${{ github.repository }}:${REVISION}@${{ steps.docker.outputs.digest }}"
        echo "🧹 Docker image \`${IMAGE}\` has been deleted" | tee -a $GITHUB_STEP_SUMMARY
      shell: bash

    - name: Cleanup docker JFrog Artifactory image
      # Runs on release failure if docker has been published
      if: failure() && steps.docker.outcome == 'success' && env.JFROG_DOCKER_REPOSITORY
      run: |
        : Cleanup docker JFrog Artifactory image
        # See:
        #   - https://jfrog.com/help/r/jfrog-rest-apis/introduction-to-the-jfrog-platform-rest-apis
        #   - https://jfrog.com/help/r/jfrog-rest-apis/delete-item
        curl -X DELETE -u ${JFROG_USER}:${JFROG_TOKEN} ${JFROG_URL}/artifactory/${JFROG_DOCKER_REPOSITORY}/${DIST}/${REVISION}
        IMAGE="${JFROG_DOMAIN}/${JFROG_DOCKER_REPOSITORY}/${DIST}:${REVISION}@${{ steps.docker.outputs.digest }}"
        echo "🧹 Docker image \`${IMAGE}\` has been deleted" | tee -a $GITHUB_STEP_SUMMARY
      shell: bash

    - name: Cleanup extra docker GHCR image
      # Runs on release failure if extra docker image has been published
      if: failure() && steps.extra-docker.outcome == 'success'
      run: |
        : Cleanup extra docker GHCR image
        # See:
        #   - https://docs.github.com/en/rest/packages/packages#list-package-versions-for-a-package-owned-by-an-organization
        #   - https://docs.github.com/en/rest/packages/packages#delete-package-version-for-an-organization
        GHAPI=("gh" "api" "-H" "Accept: application/vnd.github+json" "-H" "X-GitHub-Api-Version: 2022-11-28")
        PKG='${{ inputs.extra-docker }}'
        VERSIONS=$(${GHAPI[@]} /orgs/LedgerHQ/packages/container/${PKG}/versions)
        QUERY='.[] | select(.name == "${{ steps.extra-docker.outputs.digest }}") | .id'
        VERSION_ID=$(echo ${VERSIONS} | jq --raw-output ${QUERY})
        ${GHAPI[@]} --method DELETE /orgs/LedgerHQ/packages/container/${PKG}/versions/${VERSION_ID}
        IMAGE="ghcr.io/${{ github.repository_owner }}/${{ inputs.extra-docker }}:${REVISION}@${{ steps.extra-docker.outputs.digest }}"
        echo "🧹 Docker image \`${IMAGE}\` has been deleted" | tee -a $GITHUB_STEP_SUMMARY
      shell: bash

    - name: Cleanup extra docker JFrog Artifactory image
      # Runs on release failure if docker has been published
      if: failure() && steps.extra-docker.outcome == 'success' && env.JFROG_DOCKER_REPOSITORY
      run: |
        : Cleanup extra docker JFrog Artifactory image
        # See:
        #   - https://jfrog.com/help/r/jfrog-rest-apis/introduction-to-the-jfrog-platform-rest-apis
        #   - https://jfrog.com/help/r/jfrog-rest-apis/delete-item
        curl -X DELETE -u ${JFROG_USER}:${JFROG_TOKEN} ${JFROG_URL}/artifactory/${JFROG_DOCKER_REPOSITORY}/${{ inputs.extra-docker }}/${REVISION}
        IMAGE="${JFROG_DOMAIN}/${JFROG_DOCKER_REPOSITORY}/${{ inputs.extra-docker }}:${REVISION}@${{ steps.docker.outputs.digest }}"
        echo "🧹 Docker image \`${IMAGE}\` has been deleted" | tee -a $GITHUB_STEP_SUMMARY
      shell: bash

    - name: Cleanup JFrog Artifactory
      # Runs on release failure if package has been published to JFrog Artifactory
      if: failure() && steps.artifactory.outcome == 'success'
      run: |
        : Cleanup JFrog Artifactory
        # See:
        #   - https://jfrog.com/help/r/jfrog-rest-apis/introduction-to-the-jfrog-platform-rest-apis
        #   - https://jfrog.com/help/r/jfrog-rest-apis/delete-item
        curl -X DELETE -u ${JFROG_USER}:${JFROG_TOKEN} ${JFROG_URL}/artifactory/${JFROG_REPOSITORY}/${DIST}/${REVISION}
        echo "🧹 Package \`${DIST}==${REVISION}\` have been deleted from JFrog Artifactory \`${{ inputs.artifactory-repository }}\` repository" | tee -a $GITHUB_STEP_SUMMARY
      shell: bash

    - name: Cleanup PyPI
      # Runs on release failure if package has been published to PyPI
      if: failure() && steps.pypi.outcome == 'success'
      run: |
        : Cleanup PyPI
        # See: https://pypi.org/help/#file-name-reuse
        echo "⚠️ You need to manually delete [\`${DIST}==${REVISION}\` on PyPI](https://pypi.org/project/${DIST}/${REVISION}/)." | tee -a $GITHUB_STEP_SUMMARY
        echo "⚠️ The version is not usable anymore. See the [dedicated PyPI FAQ entry](https://pypi.org/help/#file-name-reuse)." | tee -a $GITHUB_STEP_SUMMARY
      shell: bash
