name: "Publish new version to gemfury"
description: "Publish new version to gemfury"

runs:
  using: "composite"
  steps:
    - name: Push to GemFury
      run: |
        package_file=$(find dist -type f -name "*.tar.gz")
        if [[ "$package_file" == "" ]]; then
          package_file=$(find dist -type f -name "*.whl")
        fi
        echo "Publishing package: ${package_file}"
        curl --fail -F package=@${package_file} https://${{ env.PUSH_TOKEN }}@push.fury.io/ledger/
      shell: bash
