name: Compile
description: Compiles the project
inputs:
  scala-version:
    description: Scala version to use (e.g., 2.13.8). If not set, uses the default defined in the project.
    default: ""
  memory-limit:
    description: Memory limit for sbt (2048 MB)
    default: "2048"
  cache-key:
    description: Cache key
    default: target
  upload-cache:
    description: If set, runs sbt in readonly mode
    default: "true"
  script:
    description: Script to run
  command:
    description: Compile command to run
    default: compile; Test / compile

runs:
  using: "composite"
  steps:
    - name: Cache lookup
      id: compilation-cache
      if: ${{ !contains(github.event.pull_request.body, 'ci:skip-cache') }}
      uses: /LedgerHQ/actions/scala/restore-compilation-cache@main
      with:
        key: ${{ inputs.cache-key }}-${{ inputs.scala-version }}

    - name: Compile (custom script)
      if: ${{ inputs.script != '' }}
      shell: bash
      run: ${{ inputs.script }}

    - name: Compile (main & tests)
      if: ${{ inputs.script == '' }}
      shell: bash
      run: |
        if [ "${{ inputs.scala-version }}" != "" ]; then
          sbt -mem ${{ inputs.memory-limit }} '++ ${{ inputs.scala-version }}; ${{ inputs.command }}'
        else
          sbt -mem ${{ inputs.memory-limit }} '${{ inputs.command }}'
        fi

    - name: Upload tests compilation cache
      if: ${{ inputs.upload-cache == 'true' }}
      uses: actions/cache/save@v4
      with:
        path: |
          target/scala*/*test*
          **/target/scala*/*test*
        key: ${{ inputs.cache-key }}-${{ inputs.scala-version }}-tests-${{ hashFiles('build.sbt') }}-${{ hashFiles('**/src/test/scala/**') }}

    - name: Upload main compilation cache
      if: ${{ inputs.upload-cache == 'true' }}
      uses: actions/cache/save@v4
      with:
        path: |
          target/
          **/target/
          project/target
        key: ${{ inputs.cache-key }}-${{ inputs.scala-version }}-main-${{ hashFiles('build.sbt') }}-${{ hashFiles('**/src/main/scala/**') }}
