name: Test that an helm chart renders
description: Test that an helm chart renders

inputs:
  chart-dir:
    description: Specify the chart directory.
    required: true
    default: argocd/base/
  helm-options:
    description: Specify the options to pass to helm
    required: true
    default: -f placeholder.yaml
  github-token:
    description: Specify the github token to login to ghcr.io
    required: true


runs:
  using: composite
  steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: "v3.13.3"

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ inputs.github-token }}

      - name: Run helm template
        shell: bash
        run: |
          cd ${{ inputs.chart-dir }}
          helm dependency build . && helm template . ${{ inputs.helm-options }}
