name: "Validate and publish"
description: "Run different validation steps on a app and push a docker image"

inputs:
  src-path:
    description: "path to src directory"
    required: false
    default: "src"

  redocly-project:
    description: |
      name of the project on redocly (eg "@ledger/my project@v1"),
      if empty, step is skipped
    required: false
    default: ""

  ignore-mypy:
    description: "Force ignoring Mypy step"
    required: false
    default: "false"

  docker-build-args:
    description: "args to pass to docker build"
    required: false
    default: ""

  python-version:
    description: "Version of python to use"
    required: false
    default: "3.9"

runs:
  using: "composite"
  steps:
    - uses: ./python-app/lint
      with:
        python-version: ${{ inputs.python-version }}

    - uses: ./python-app/test
      with:
        src-path: ${{ inputs.src-path }}
        ignore-mypy: ${{ inputs.ignore-mypy }}
        python-version: ${{ inputs.python-version }}

    - uses: ./python-app/goss
      with:
        GOSS_IMAGE: goss_image:latest
        GOSS_FILES_PATH: .github/goss

    - uses: ./python-app/docker
      with:
        build-args: ${{ inputs.docker-build-args }}

    - uses: ./python-app/doc
      with:
        redocly-project: ${{ inputs.redocly-project }}
