name: "Validate and publish"
description: "Run different validation steps on a app and push a docker image"

inputs:
  src-path:
    description: "path to src directory"
    required: false
    default: "src"
  python-version:
    required: false
    default: "3.10"
  report-format: 
    description: "test report format"
    required: false
    default: "xml"

  redocly-project:
    description: |
      name of the project on redocly (eg "@ledger/my project@v1"),
      if empty, step is skipped
    required: false
    default: ""

  test-report-format:
    description: "format of the report test generated"
    required: false

  ignore-mypy:
    description: "Force ignoring Mypy step"
    required: false
    default: "false"

  docker-build-args:
    description: "args to pass to docker build"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: pipenv
      uses: LedgerHQ/actions/python-app/init@secret-support

    - uses: LedgerHQ/actions/python-app/lint@secret-support

    - uses: LedgerHQ/actions/python-app/test@secret-support
      with:
        src-path: ${{ inputs.src-path }}
        ignore-mypy: ${{ inputs.ignore-mypy }}

    - uses: LedgerHQ/actions/python-app/goss@secret-support
      with:
        GOSS_IMAGE: goss_image:latest
        GOSS_FILES_PATH: .github/goss

    - uses: LedgerHQ/actions/python-app/docker@secret-support
      with:
        build-args: ${{ inputs.docker-build-args }}

    - uses: LedgerHQ/actions/python-app/doc@secret-support
      with:
        redocly-project: ${{ inputs.redocly-project }}
