name: Doc
description: Publish documentation

inputs:
  redocly-project:
    description: |
      name of the project on redocly (eg "@ledger/my project@v1"),
      if empty, step is skipped
    required: false
    default: ""

  python-version:
    description: "Version of python to use"
    required: false
    default: "3.9"

runs:
  using: "composite"

  steps:
    - name: Check if step is needed
      id: check-doc
      run: |
        echo "::set-output name=is-doc-needed::${{ inputs.redocly-project != '' && startsWith(github.ref, 'refs/tags/') }}"
      shell: bash

    - if: ${{ steps.check-doc.outputs.is-doc-needed == 'true' }}
      name: pipenv
      uses: LedgerHQ/actions/python-app/init@main
      with:
        python-version: ${{ inputs.python-version }}

    - if: ${{ steps.check-doc.outputs.is-doc-needed == 'true' }}
      name: Generate openapi
      run: |
        pipenv run openapi
      shell: bash

    - if: ${{ steps.check-doc.outputs.is-doc-needed == 'true' }}
      name: Setup Node.js
      uses: actions/setup-node@v2

    - if: ${{ steps.check-doc.outputs.is-doc-needed == 'true' }}
      name: Publish to redocly
      run: npx @redocly/openapi-cli@latest push doc/api-spec.yaml "${{ inputs.redocly-project }}"
      shell: bash
