name: "C4"
description: "Generate C4 PNG files"

inputs:
  doc_path:
    description: "Specify the path where the .puml files are located."
    required: false
    default: "doc"

runs:
  using: "composite"
  steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: generate png diagrams
        uses: Timmy/plantuml-action@v1
        with:
          args: "-tpng ${{ inputs.doc_path }}/*.puml"

      - name: push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[bot] update documentation"
          file_pattern: "${{ inputs.doc_path }}/*.png"
