name: OpenAPI Diff
description: Generate a diff between 2 OpenAPI specifications

inputs:
  base:
    description: Base diff specification file
    required: true
  head:
    description: Head diff specification file
    required: true
  output:
    description: Output directory
    required: true
    default: reports/openapi
  github-token:
    description: "A GitHub token with `pull-requests: write` permissions"
    default: ${{ github.token }}

outputs:
  markdown:
    description: Path to the generated markdown diff file
    value: ${{ steps.generate.outputs.markdown }}
  text:
    description: Path to the generated text diff file
    value: ${{ steps.generate.outputs.text }}
  comment:
    description: Path to the generated PR comment file
    value: ${{ steps.generate.outputs.comment }}

runs:
  using: "composite"

  steps:
    - name: Create outputs directory
      run: |
        mkdir -p "${{ inputs.output }}"
      shell: bash

    - name: Run OpenAPI diff
      id: generate
      run: |
        set -e  # Exit on any error

        echo "Pulling openapitools image"
        docker pull openapitools/openapi-diff:latest

        echo "Generating Markdown diff"
        md_output="${{ inputs.output }}/diff.md"

        docker run --rm -t \
          -v "${{ github.workspace }}":/specs \
          openapitools/openapi-diff:latest --off \
          --markdown "/specs/${md_output}" \
          "/specs/${{ inputs.base }}" \
          "/specs/${{ inputs.head }}"

        echo "markdown=${md_output}" >> "$GITHUB_OUTPUT"

        # Format diff as PR comment
        comment="${{ inputs.output }}/pr-comment.md"
        echo "## OpenAPI changes" > "${comment}"
        cat "${md_output}" >> "${comment}"
        echo "comment=${comment}" >> "$GITHUB_OUTPUT"

        # Display diff in the summary
        cat "${comment}" >> "$GITHUB_STEP_SUMMARY"

        echo "Generating text diff"
        txt_output="${{ inputs.output }}/diff.txt"
        docker run --rm -t \
          -v "${{ github.workspace }}":/specs \
          openapitools/openapi-diff:latest --off \
          --text "/specs/${txt_output}" \
          "/specs/${{ inputs.base }}" \
          "/specs/${{ inputs.head }}"
        echo "text=${txt_output}" >> "$GITHUB_OUTPUT"
      shell: bash

    - name: Comment PR with OpenAPI diff
      if: github.event_name == 'pull_request'
      uses: thollander/actions-comment-pull-request@v3
      with:
        file-path: ${{ steps.generate.outputs.comment }}
        comment-tag: openapi-diff
        github-token: ${{ inputs.github-token }}

    - uses: actions/upload-artifact@v4
      with:
        name: openapi-diff
        path: |
          ${{ steps.generate.outputs.markdown }}
          ${{ steps.generate.outputs.text }}
        retention-days: 10
