name: "lint"
description: "run pre-commit hooks"

inputs:
  python-version:
    description: "Version of python to use"
    required: false
    default: "3.9"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
    - uses: pre-commit/action@v3.0.0
