name: Lint
description: Lint running pre-commit hooks

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v6
      with:
        python-version-file: pyproject.toml
    - name: Lint with pre-commit
      uses: pre-commit/action@v3.0.1
