name: "Compute git metadata"
description: "Compute git metadata for a PR as output"
outputs:
  target:
    description: "Target of the PR, if any"
    value: ${{ steps.refs.outputs.target }}
  branch:
    description: "Branch that triggered the action"
    value: ${{ steps.refs.outputs.branch }}
  version:
    description: "Version tagging the commit that triggered the action"
    value: ${{ steps.refs.outputs.version }}
  sha:
    description: "SHA of the commit that triggered the action"
    value: ${{ steps.refs.outputs.sha }}
  refs:
    description: "JSON containing all the former values"
    value: ${{ toJson(steps.refs.outputs) }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: Compute base ref (branch/tag) name
      id: refs
      run: |
        if  [[ $GITHUB_EVENT_NAME == 'pull_request' ]]; then
          echo "target=origin/${GITHUB_BASE_REF#refs/heads/}" >> $GITHUB_OUTPUT
        elif  [[ $GITHUB_REF == refs/heads/feature/* ]]; then
          echo "target=main" >> $GITHUB_OUTPUT
        else
          echo "target=HEAD^" >> $GITHUB_OUTPUT
        fi

        if  [[ $GITHUB_EVENT_NAME == 'pull_request' ]]; then
          branch=${GITHUB_HEAD_REF#refs/heads/}
          # Workaround https://github.com/actions/checkout/issues/299 and https://github.com/actions/checkout/issues/237
          sha=${{ github.event.pull_request.head.sha }}
        elif [[ $GITHUB_REF == refs/heads/* ]]; then
          branch=${GITHUB_REF#refs/heads/}
          sha=${{ github.sha }}
        fi

        if [[ $GITHUB_REF == refs/tags/* ]]; then
          # It's a tag aka. a semver dotted release (X.Y.Z assuming no v prefix)
          version=${GITHUB_REF#refs/tags/}
          echo "branch=${version}" >> $GITHUB_OUTPUT
          echo "version=${version}" >> $GITHUB_OUTPUT
          echo "sha=${{ github.sha }}" >> $GITHUB_OUTPUT
        elif [[ ! -z "$branch" ]]; then
          echo "branch=${branch}" >> $GITHUB_OUTPUT
          echo "version=${branch//\//-}-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "sha=${sha}" >> $GITHUB_OUTPUT
        else
          echo "::error ::Unkown case: current build is neither a tag, a branch or a pull request"
          exit 1
        fi
      shell: bash
    - name: Display output
      run: echo "${{ toJson(steps.refs.outputs) }}"
      shell: bash
