name: "Run Helm Chart Testing & Docs"
description: "Run Helm Chart Testing & Docs"

inputs:
  charts-dir:
    description: "Specify the charts directory."
    required: true
    default: "helm/charts/"
  helm-docs-version:
    description: "Specify the helm-docs version that you want to use."
    required: true
    default: "1.11.0"

runs:
  using: "composite"
  steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.13.1

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Run chart-testing (lint)
        shell: bash
        run: ct lint --chart-dirs=${{ inputs.charts-dir }} --check-version-increment=false --target-branch=main --remote=origin

      - name: Run helm-docs
        shell: bash
        env:
          HELM_DOCS_VERSION: ${{ inputs.helm-docs-version }}
          HELM_DOCS_BASE_URL: "https://github.com/norwoodj/helm-docs/releases/download"
        run: |
          OS=$(uname)
          # install helm-docs
          curl -sSfL "${HELM_DOCS_BASE_URL}/v${HELM_DOCS_VERSION}/helm-docs_${HELM_DOCS_VERSION}_${OS}_x86_64.tar.gz" |
          tar -xzf - helm-docs
          # validate docs
          ./helm-docs
          git diff --exit-code
