name: 'Generate SDK from OpenAPI spec'
description: 'Generate Python SDK from OpenAPI specification with customizable templates'

inputs:
  openapi-artifact-name:
    description: 'Name of the artifact containing the OpenAPI spec'
    required: true
  templates-repo:
    description: 'Repository containing SDK generation templates'
    required: false
    default: 'LedgerHQ/ledger-sdk-template'
  templates-ref:
    description: 'Branch/tag/commit of the templates repository'
    required: false
    default: 'main'
  templates-path:
    description: 'Path within templates repository to the templates directory'
    required: false
    default: 'python/templates'
  project-name:
    description: 'Name of the generated SDK project'
    required: true
  package-name:
    description: 'Python package name for the SDK'
    required: true
  output-path:
    description: 'Output directory for the generated SDK'
    required: false
    default: 'sdk'
  python-version:
    description: 'Python version to use for SDK generation'
    required: false
    default: '3.12'
  generate-tests:
    description: 'Whether to generate test suite'
    required: false
    default: 'true'
  run-tests:
    description: 'Whether to run the generated tests'
    required: false
    default: 'true'
  upload-artifact:
    description: 'Whether to upload the generated SDK as an artifact'
    required: false
    default: 'true'
  artifact-name:
    description: 'Name for the uploaded SDK artifact'
    required: false
    default: 'python-sdk'
  github-token:
    description: A Github token with proper permissions
    required: false
    default: ${{ github.token }}

outputs:
  sdk-path:
    description: 'Path to the generated SDK'
    value: ${{ steps.generate.outputs.sdk-path }}
  artifact-name:
    description: 'Name of the uploaded artifact'
    value: ${{ steps.upload.outputs.artifact-name }}

runs:
  using: 'composite'
  steps:
    - name: Init PDM
      uses: LedgerHQ/actions/pdm/init@generate-sdk-action
      with:
        python-version: ${{ inputs.python-version }}
        repository: ${{ inputs.templates-repo }}
        working-directory: ./python

    - name: Download OpenAPI artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.openapi-artifact-name }}

    - name: Locate OpenAPI spec file
      shell: bash
      id: locate-spec
      run: |
        # Find the OpenAPI spec file in the downloaded artifact
        spec_file=$(find . -name "*.yaml" -o -name "*.yml" -o -name "*.json" | head -1)
        if [ -z "$spec_file" ]; then
          echo "Error: No OpenAPI spec file found in artifact"
          exit 1
        fi
        echo "spec-file=$spec_file" >> $GITHUB_OUTPUT

    - name: Generate SDK
      id: generate
      working-directory: ./python
      run: |
        : Generate SDK from OpenAPI spec
        pdm sdk:client ${{steps.locate-spec.outputs.spec-file }}
        pdm sdk:model ${{steps.locate-spec.outputs.spec-file }}
        pdm sdk:build
      shell: bash
branding:
  icon: 'package'
  color: 'blue'
