name: "Build and publish Helm Chart"

inputs:
  release:
    type: boolean
    required: false
    default: false
  version:
    type: string
    required: false
  chart-testing-config:
    type: string
    required: false
    default: ".github/ct.yaml"
  charts-path:
    type: string
    required: false
    default: "./helm/charts/"

jobs:
  lint-chart:
    runs-on: [self-hosted, shared]
    steps:
      - name: Run Chart lint
        uses: LedgerHQ/actions/helm/lint@slu-reusable-helm-workflow
        with:
          chart-testing-config: ${{inputs.chart-testing-config}}
      - name: Run K8 conformity
        uses: LedgerHQ/actions/helm/conform@slu-reusable-helm-workflow
  publish-dev:
    runs-on: [self-hosted, shared]
    needs: [lint-chart]
    steps:
      - name: Push chart to chartmuseum-prd repo
        uses: LedgerHQ/actions/helm/publish-cm@slu-reusable-helm-workflow
        environment: dev
        if: inputs.version != ''
        with:
          version: ${{ inputs.version }}
          chartmuseum-url: ${{ secrets.CHARTMUSEUM_URL }}
          chartmuseum-user: ${{ secrets.CHARTMUSEUM_USER }}
          chartmuseum-password: ${{ secrets.CHARTMUSEUM_PASSWORD }}
          force: false
          charts-path: ${{ inputs.charts-path }}
  publish-prd:
    runs-on: [self-hosted, shared]
    needs: [publish-dev, lint-chart]
    steps:
      - name: Push chart to chartmuseum-prd repo
        environment: prd
        if: inputs.version != '' && inputs.release != false
        uses: LedgerHQ/actions/helm/publish-cm@slu-reusable-helm-workflow
        with:
          version: ${{ inputs.version }}
          chartmuseum-url: ${{ secrets.CHARTMUSEUM_URL }}
          chartmuseum-user: ${{ secrets.CHARTMUSEUM_USER }}
          chartmuseum-password: ${{ secrets.CHARTMUSEUM_PASSWORD }}
          charts-path: ${{ inputs.charts-path }}
          force: false

