name: "Build and publish Helm Chart"

inputs:
  release:
    type: boolean
    required: false
    default: false
  version:
    type: string
    required: false
  chart-testing-config:
    type: string
    required: false
    default: ".github/ct.yaml"

runs:
  using: "composite"
  strategy:
    matrix:
      k8s:
        - v1.22.4
        - v1.23.0
        - v1.24.0
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Run Chart lint
      uses: LedgerHQ/actions/helm/lint@slu
      with:
        chart-testing-config: ${{inputs.chart-testing-config}}
    - name: Run K8 conformity
      uses: LedgerHQ/actions/helm/conform@slu
      with:
        kubernetes-version: ${{ matrix.k8s }}
    - name: Push chart to chartmuseum-prd repo
      uses: LedgerHQ/actions/helm/publish-cm@slu
      environment: dev
      if: inputs.version != ''
      with:
        version: ${{ inputs.version }}
        chartmuseum-url: ${{ secrets.CHARTMUSEUM_URL }}
        chartmuseum-user: ${{ secrets.CHARTMUSEUM_USER }}
        chartmuseum-password: ${{ secrets.CHARTMUSEUM_PASSWORD }}
        force: false
    - name: Push chart to chartmuseum-prd repo
      environment: prd
      if: inputs.version != '' && inputs.release != false
      uses: LedgerHQ/actions/helm/publish-cm@slu
      with:
        version: ${{ inputs.version }}
        chartmuseum-url: ${{ secrets.CHARTMUSEUM_URL }}
        chartmuseum-user: ${{ secrets.CHARTMUSEUM_USER }}
        chartmuseum-password: ${{ secrets.CHARTMUSEUM_PASSWORD }}
        force: false
