name: Documentation
description: Build and publish documentation

inputs:
  working-directory:
    description: Working directory for the project (relative to repo root)
    default: '.'
  version:
    description: Force a version to be built
    required: false
  openapi:
    description: Has OpenAPI specs
    default: 'false'
  site:
    description: Publish a documentation site
    default: 'false'
  init:
    description: Clone & sync
    default: 'true'
  python-version:
    description: Python version used to build

outputs:
  url:
    description: The published documentation URL
    value: ${{ steps.publish.outputs.url }}

runs:
  using: "composite"
  steps:
    - uses: LedgerHQ/actions/pdm/doc/build@main
      with:
        working-directory: ${{ inputs.working-directory }}
        init: ${{ inputs.init }}
        python-version: ${{ inputs.python-version }}
        openapi: ${{ inputs.openapi }}
        site: ${{ inputs.site }}
    - uses: LedgerHQ/actions/pdm/doc/publish@main
      id: publish
      with:
        working-directory: ${{ inputs.working-directory }}
        init: false
        openapi: ${{ inputs.openapi }}
        site: ${{ inputs.site }}
        version: ${{ inputs.version }}
