name: _Build and publish Helm Chart

on:
  workflow_call:
    inputs:
      release:
        type: boolean
        required: false
        default: false
      version:
        type: string
        required: false
      charts-path:
        type: string
        required: false
        default: "./helm/charts/"

jobs:
  publish-chartmuseum-dev:
    name: publish-chartmuseum-dev
    environment: chartmuseum-dev
    if: inputs.version != ''
    runs-on: [shared]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Push chart to chartmuseum-prd repo
        uses: LedgerHQ/actions/helm/publish-cm@add-reusable-workflow-helm
        with:
          charts-path: ${{inputs.charts-path}}
          version: ${{ inputs.version }}
          chartmuseum-url: ${{ secrets.CHARTMUSEUM_DEV_URL }}
          chartmuseum-user: ${{ secrets.CHARTMUSEUM_DEV_USER }}
          chartmuseum-password: ${{ secrets.CHARTMUSEUM_DEV_PASSWORD }}
          force: true

  publish-chartmuseum-prd:
    name: publish-chartmuseum-prd
    environment: chartmuseum-prd
    if: inputs.version != '' && inputs.release != false
    runs-on: [shared]
    needs: [publish-chartmuseum-dev]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Push chart to chartmuseum-prd repo
        uses: LedgerHQ/actions/helm/publish-cm@add-reusable-workflow-helm
        with:
          charts-path: ${{inputs.charts-path}}
          version: ${{ inputs.version }}
          chartmuseum-url: ${{ secrets.CHARTMUSEUM_PROD_URL }}
          chartmuseum-user: ${{ secrets.CHARTMUSEUM_PROD_USER }}
          chartmuseum-password: ${{ secrets.CHARTMUSEUM_PROD_PASSWORD }}
          force: true
