name: _Build and publish Helm Chart

on:
  workflow_call:
    inputs:
      chart-testing-config:
        type: string
        required: false
        default: ".github/ct.yaml"
      charts-path:
        type: string
        required: false
        default: "./helm/charts/"

jobs:
  lint-chart:
    runs-on: [shared]
    steps:
      - name: Register dependencies repository
        shell: bash
        run: |
          if [ ! -z "${{ secrets.DEV_CHARTMUSEUM_URL }}" ]; then
            helm repo add dev-chartmuseum --username ${{ secrets.DEV_CHARTMUSEUM_USER }} --password ${{ secrets.DEV_CHARTMUSEUM_PASSWORD }} ${{ secrets.DEV_CHARTMUSEUM_URL }}
            helm repo update
          fi
          if [ ! -z "${{ secrets.PROD_CHARTMUSEUM_URL }}" ]; then
            helm repo add prd-chartmuseum --username ${{ secrets.PROD_CHARTMUSEUM_USER }} --password ${{ secrets.PROD_CHARTMUSEUM_PASSWORD }} ${{ secrets.PROD_CHARTMUSEUM_URL }}
            helm repo update
          fi
      - name: Run Chart lint
        uses: LedgerHQ/actions/helm/lint@add-reusable-workflow-helm
        with:
          chart-testing-config: ${{inputs.chart-testing-config}}

  kubeconform-chart:
    runs-on: [shared]
    strategy:
      matrix:
        k8s:
          - v1.23.0
          - v1.24.0
    steps:
      - name: Register dependencies repository
        shell: bash
        run: |
          if [ ! -z "${{ secrets.PROD_CHARTMUSEUM_URL }}" ]; then
            helm repo add chartmuseum --username ${{ secrets.PROD_CHARTMUSEUM_USER }} --password ${{ secrets.PROD_CHARTMUSEUM_PASSWORD }} ${{ secrets.PROD_CHARTMUSEUM_URL }}
            helm repo update
          fi
      - name: Run Kubeconform
        uses: LedgerHQ/actions/helm/conform@add-reusable-workflow-helm
        with:
          kubernetes-version: ${{ matrix.k8s }}
          charts-path: ${{inputs.charts-path}}
