name: Test allure action

on:
  push:
    branches: [ main ]
    paths: [ allure/** ]
  pull_request:
    branches: [ main ]
    paths: [ allure/** ]

defaults:
  run:
    working-directory: allure

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Test new version of the action
        run: echo "Nothing to do"
