name: Test python-app action

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/**'
    paths:
      - 'python-app/**'
  pull_request:
    branches:
      - main
      - 'feature/**'
    tags:
      - '*'
    paths:
      - 'python-app/**'

defaults:
  run:
    working-directory: python-app

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Test building the new action
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.CI_BOT_TOKEN }}
          repository : LedgerHQ/test-actions
          event-type: build-app
          client-payload : '{"ref": "${{ github.ref }}", "sha": "${{ github.sha}}"}'
