name: "Test and publish Helm Chart"

on:
  workflow_call:
    inputs:
      release:
        type: boolean
        required: false
        default: false
      version:
        type: string
        required: false
      charts-path:
        type: string
        required: false
        default: "helm/charts/"

jobs:
  lint-chart:
    runs-on: [self-hosted, shared]
    steps:
      - name: Run Chart lint
        uses: LedgerHQ/actions/helm/lint@main
        with:
          charts-dir: ${{ inputs.charts-path }}

  kubeconform-chart:
    runs-on: [self-hosted, shared]
    strategy:
      matrix:
        k8s:
          - v1.27.9
          - v1.26.12
          - v1.25.16
    steps:
      - name: Run the helm conform
        uses: LedgerHQ/actions/helm/conform@main
        with:
          kubernetes-version: ${{ matrix.k8s }}
          charts-path: ${{ inputs.charts-path }}

  publish-chartmuseum-dev:
    name: publish-chartmuseum-dev
    if: inputs.version != ''
    runs-on: [self-hosted, shared]
    needs: [lint-chart, kubeconform-chart]
    steps:
      - name: Push chart to chartmuseum-prd repo
        uses: LedgerHQ/actions/helm/publish-cm@main
        with:
          charts-path: ${{ inputs.charts-path }}
          version: ${{ inputs.version }}
          chartmuseum-url: ${{ secrets.CHARTMUSEUM_DEV_URL }}
          chartmuseum-user: ${{ secrets.CHARTMUSEUM_DEV_USER }}
          chartmuseum-password: ${{ secrets.CHARTMUSEUM_DEV_PASSWORD }}
          force: ${{ startsWith(inputs.version, '0.0.0' ) }}

  publish-chartmuseum-prd:
    name: publish-chartmuseum-prd
    if: inputs.version != '' && inputs.release != false
    runs-on: [self-hosted, shared]
    needs: [publish-chartmuseum-dev]
    steps:
      - name: Push chart to chartmuseum-prd repo
        uses: LedgerHQ/actions/helm/publish-cm@main
        with:
          charts-path: ${{ inputs.charts-path }}
          version: ${{ inputs.version }}
          chartmuseum-url: ${{ secrets.CHARTMUSEUM_PROD_URL }}
          chartmuseum-user: ${{ secrets.CHARTMUSEUM_PROD_USER }}
          chartmuseum-password: ${{ secrets.CHARTMUSEUM_PROD_PASSWORD }}
          force: startsWith( ${{ inputs.version }}, '0.0.0' )
