name: "Test and publish Helm Chart"

on:
  workflow_call:
    inputs:
      release:
        type: boolean
        required: false
        default: false
      version:
        type: string
        required: false
      chart-testing-config:
        type: string
        required: false
        default: ".github/ct.yaml"
      charts-path:
        type: string
        required: false
        default: "./helm/charts/"

jobs:
  lint-chart:
    runs-on: [self-hosted, shared]
    steps:
      - name: Run Chart lint
        uses: LedgerHQ/actions/helm/lint@main
        with:
          chart-testing-config: ${{inputs.chart-testing-config}}

  kubeconform-chart:
    runs-on: [self-hosted, shared]
    strategy:
      matrix:
        k8s:
          - v1.24.17
          - v1.23.17
    steps:
      - name: Run the helm conform
        uses: LedgerHQ/actions/helm/conform@main
        with:
          kubernetes-version: ${{ matrix.k8s }}
          charts-path: ${{ inputs.charts-path }}
        
  publish-chartmuseum-dev:
    name: publish-chartmuseum-dev
    environment: dev
    if: inputs.version != ''
    runs-on: [self-hosted, shared]
    needs: [lint-chart, kubeconform-chart]
    steps:
      - name: Push chart to chartmuseum-prd repo
        uses: LedgerHQ/actions/helm/publish-cm@main
        with:
          charts-path: ${{ inputs.charts-path }}
          version: ${{ inputs.version }}
          chartmuseum-url: ${{ secrets.CHARTMUSEUM_URL }}
          chartmuseum-user: ${{ secrets.CHARTMUSEUM_USER }}
          chartmuseum-password: ${{ secrets.CHARTMUSEUM_PASSWORD }}
          force: true

  publish-chartmuseum-prd:
    name: publish-chartmuseum-prd
    environment: prd
    if: inputs.version != '' && inputs.release != false
    runs-on: [self-hosted, shared]
    needs: [publish-chartmuseum-dev]
    steps:
      - name: Push chart to chartmuseum-prd repo
        uses: LedgerHQ/actions/helm/publish-cm@main
        with:
          charts-path: ${{ inputs.charts-path }}
          version: ${{ inputs.version }}
          chartmuseum-url: ${{ secrets.CHARTMUSEUM_URL }}
          chartmuseum-user: ${{ secrets.CHARTMUSEUM_USER }}
          chartmuseum-password: ${{ secrets.CHARTMUSEUM_PASSWORD }}
          force: false
